---
- name: "create project dir"
  raw: mkdir ~/backend
  args:
    executable: /bin/bash

- name: "send build atrifacts to remote"
  unarchive:
    src: ../../artifact.tar.gz
    dest: ~/backend

- name: "install backend artifacts"
  npm:
    path: ~/backend
    production: true
    global: true

- name: "start the app"
  raw: (cd ~/backend && pm2 stop all; pm2 start npm -- run start)
  args:
    executable: /bin/bash