---
- name: "send build atrifacts to remote"
  copy:
    src: ../../artifact.tar.gz
    dest: ~/artifact.tar.gz

# - name: "upgrade tar and install gzip."
#   become: true
#   apt:
#     pkg:
#       - gzip
#       - tar
#     state: latest
#     update_cache: true

- name: "Extract build atrifacts"
  raw: (mkdir ~/backend && tar -zxvf ~/artifact.tar.gz -C ~/backend)
  args:
    executable: /bin/bash

- name: "install backend artifacts"
  npm:
    path: ~/backend
    production: true

- name: "start the app"
  raw: (cd ~/backend && pm2 stop default; pm2 start npm -- start)
  args:
    executable: /bin/bash
